server:
  servlet:
    port: 8081
    contextPath: /ims
---
spring:
  profiles: local
datasource:
  sampleapp:
    url: jdbc:postgresql://localhost:5432/db_devovate
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/ims_dev?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      ddl-auto: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect